project:
  type: website
  output-dir: docs

resources:
  - googlee24fe4eb9bc657e0.html

website:
  title: "Jiakai Chen"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
